- name: dotfiles
  become_user: oezguer
  ansible.builtin.copy:
    src: "~/dotfiles"
    dest: "~/"
    force: true

- name: zshrc
  become_user: oezguer
  ansible.builtin.copy:
    src: "~/dotfiles/.zshrc"
    dest: "~/.zshrc"
    force: true
