- name: dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/oezguerisbert/dotfiles.git'
    dest: "~/repositories/github.com/oezguerisbert/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: distributing dotfiles
  shell: "sudo rsync -a ~/repositories/github.com/oezguerisbert/dotfiles/ ~/ && sudo rm -rf ~/.git && sudo rm -rf ~/.gitignore"

- name: setup Neovim
  shell: "curl -fLo {{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
