- name: Git personal setup email
  become_user: oezguer
  git_config:
    name: user.email
    scope: global
    value: "oezguerisbert@gmail.com"
  tags:
  - git-personal

- name: Git personal setup name
  become_user: oezguer
  git_config:
    name: user.name
    scope: global
    value: "Özgür Isbert"
  tags:
  - git-personal

- name: Git set main branch name
  become_user: oezguer
  git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
  - git-personal
