- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
