- name: Remove neovim
  shell: rm -rf ~/repositories/github.com/neovim/neovim
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/repositories/github.com/neovim/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/repositories/github.com/neovim/neovim && make -j 8"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/repositories/github.com/neovim/neovim && make install"


